Diffbot knowledge graph url is updated to new url from deprecated url
theRealPadster/diffbot-api-node pull request #27
Opened 2023-08-25 13:35 UTC by mustafa-colakoglu

Hi, diffbot knowledge graph url is deprecated and not working now, you should use new one.

2023-08-28 21:32 UTC, theRealPadster requested changes
Thanks for this! Could you keep the indentation the same and update the URL in `test/knowledge-graph.test.js`?

2023-08-28 21:32 UTC, theRealPadster commented on src/diffbot.js
> +      let diffbot_url = `https://kg.diffbot.com/kg/v3/dql?token=${this.token}&query=${encodeURIComponent(options.query)}`;
```suggestion
    let diffbot_url = `https://kg.diffbot.com/kg/v3/dql?token=${this.token}&query=${encodeURIComponent(options.query)}`;
```

2023-08-29 09:32 UTC, mustafa-colakoglu commented on src/diffbot.js
> +      let diffbot_url = `https://kg.diffbot.com/kg/v3/dql?token=${this.token}&query=${encodeURIComponent(options.query)}`;
h,, can you review again

2023-08-29 21:05 UTC, theRealPadster approved these changes
Looks good thanks 👍

2023-08-29 21:06 UTC, merged

2023-08-29 22:23 UTC, mustafa-colakoglu commented
@theRealPadster i want to ask, is this changes uploaded to npm? maybe yo should update the version maybe

2023-08-30 00:40 UTC, theRealPadster commented
@mustafa-colakoglu I didn't publish a new version yet. I was planning on finishing adding GitHub action workflows first. Hoping to get that added in tomorrow and then publish a new version

2023-08-30 01:05 UTC, mustafa-colakoglu commented
> @mustafa-colakoglu I didn't publish a new version yet. I was planning on finishing adding GitHub action workflows first. Hoping to get that added in tomorrow and then publish a new version

Okay, I am waiting for new version, because we are using this library on our project

2023-08-30 05:13 UTC, theRealPadster commented
@mustafa-colakoglu I've published 0.9.4 on npm, so you should be good to go now :)